<?php

/**
 * BaseTasksTask
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * @property boolean $is_done
 * @property timestamp $created_at
 * @property timestamp $due_at
 * 
 * @method string    getTitle()       Returns the current record's "title" value
 * @method string    getDescription() Returns the current record's "description" value
 * @method boolean   getIsDone()      Returns the current record's "is_done" value
 * @method timestamp getCreatedAt()   Returns the current record's "created_at" value
 * @method timestamp getDueAt()       Returns the current record's "due_at" value
 * @method TasksTask setTitle()       Sets the current record's "title" value
 * @method TasksTask setDescription() Sets the current record's "description" value
 * @method TasksTask setIsDone()      Sets the current record's "is_done" value
 * @method TasksTask setCreatedAt()   Sets the current record's "created_at" value
 * @method TasksTask setDueAt()       Sets the current record's "due_at" value
 * 
 * @package    tasks
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTasksTask extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tasks_task');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('is_done', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('created_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('due_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}