<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/09/03 16:36:23

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=tasks',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
