<?php

/**
 * TasksTaskTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TasksTaskTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TasksTaskTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TasksTask');
    }
}