TasksTask
  actAs: { Timestampable: ~ }
  columns:
    task_id: { type: integer, notnull: true }
    title: { type: string(255), notnull: true }
    description: { type: string(4000) } 
    is_done: { type: boolean, notnull: true, default: 0 }
    created_at: { type: timestamp, notnull: true }
    due_at: { type: timestamp }
